kind: Deployment
apiVersion: apps/v1
metadata:
    labels:
        app: {{.Release.Name}}-microservice
        release: {{.Values.releaseType}}
        version: "{{.Values.tag}}"
        stack: frontend
        source: demo
    name: {{.Release.Name}}-microservice
    namespace: microservices
spec:
    replicas: 3
    selector:
        matchLabels:
            run: {{.Release.Name}}-microservice
    template:
        metadata:
            labels:
                app: {{.Release.Name}}-microservice
                run: {{.Release.Name}}-microservice
                source: demo
        spec:
            containers:
                - name: {{.Release.Name}}-microservice
                  {{- $valtag := .Values.tag -}}
                  {{- if $valtag}}
                  image: {{.Values.ecr}}/{{.Release.Name}}-microservice:{{ $valtag }}"
                  {{- else}}
                  image: {{.Values.ecr}}/{{.Release.Name}}-microservice
                  {{- end}}
                  ports:
                    -   name: web
                        containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
    labels:
        app: {{.Release.Name}}-microservice-service
        release: {{.Values.releaseType}}
        version: "{{.Values.tag}}"
    name: {{.Release.Name}}-microservice-service
    namespace: microservices
spec:
    selector:
        source: demo
        app: {{.Release.Name}}-microservice
    ports:
        -   name: web
            protocol: TCP
            port: 30201
            targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    name: {{.Release.Name}}-ingress
    namespace: microservices
spec:
    ingressClassName: nginx
    rules:
        -   http:
                paths:
                    - pathType: Prefix
                      path: /{{.Release.Name}}(/|$)(.*)
                        backend:
                            service: 
                                name: {{.Release.Name}}-microservice-service 
                                port: 
                                    number: 30201


