kind: Deployment
apiVersion: apps/v1
metadata:
    labels:
        app: mild-temper-microservice
        stack: frontend
        source: demo
    name: mild-temper-microservice
    namespace: microservices
spec:
    replicas: 3
    selector:
        matchLabels:
            run: mild-temper-microservice
            strategy.spinnaker.io/max-version-history: '10'
            traffic.spinnaker.io/load-balancers: '["service mild-temper-microservice-service"]'
    template:
        metadata:
            labels:
                app: mild-temper-microservice
                run: mild-temper-microservice
                source: demo
        spec:
            containers:
                -   image: 219099013464.dkr.ecr.us-west-2.amazonaws.com/mild-temper-microservice
                    name: mild-temper-microservice
                    ports:
                        -   name: web
                            containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
    labels:
        app: mild-temper-microservice-service
    name: mild-temper-microservice-service
    namespace: microservices
spec:
    selector:
        source: demo
        app: mild-temper-microservice
    ports:
        -   name: web
            protocol: TCP
            port: 30201
            targetPort: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    name: mild-temper-ingress
    namespace: microservices
spec:
    rules:
        -   http:
                paths:
                    -   path: /mild-temper(/|$)(.*)
                        backend:
                            serviceName: mild-temper-microservice-service
                            servicePort: 30201


